# Generated by Django 3.0.5 on 2022-06-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gara', '0028_auto_20220601_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaBCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.BaoCaoTon'),
        ),
        migrations.AlterField(
            model_name='ct_baocaoton',
            name='MaVTPT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='ct_vattuphutung',
            name='mavattuphutung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
        migrations.AlterField(
            model_name='phieunhapvtpt',
            name='mavattuphutung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gara.VatTuPhuTung'),
        ),
    ]
